# See https://github.com/orgs/community/discussions/26539
name: publish-feeds

on:
  schedule:
    # https://cron.help/#33_2/6_*_*_*
    # "At :33 in every 6th hour from 2am through 11pm"
    - cron: "33 2/6 * * *"
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish_environment

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9 #install the python needed

      # https://github.com/marketplace/actions/install-poetry-action
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: execute python script
        run: |
          poetry install
          dig railroads.dot.gov
          sh generate.sh
          poetry run python upload.py
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
